### ISSUE TITLE
Dominant highlighted when the lydian scale selected

### ISSUE THREAD

**Issue by DmitryRosenblatt** [zetmate/guitar-scale#1]
**Steps to reproduce:**
1) Select scale that have dominant highlight (major for e.g.)
2) Select the lydian scale using the same root note

**Result:**
Dominant highlighted when the lydian scale selected

**Expected result:**
The note that was dominant for previous scale is highlighted as a regular note when the lydian scale selected

![Dominant highlighted bug](https://github.com/user-attachments/assets/6765b999-1ada-4fa9-abe9-77823166559a)

**Comment by zetmate** [comment]
note for myself: it's a typo in the condition for showing the settings
```
{(scale.degreesInfo.hasSubdominant ||
                scale.degreesInfo.hasSubdominant) && (
```
(subdominant is checked twice - copy-paste issue)

**Comment by zetmate** [comment]
fixed

**Comment by zetmate** [comment]
fixed
