### ISSUE TITLE
Incorrect note naming when the double harmonic scale is selected

### ISSUE THREAD

**Issue by DmitryRosenblatt** [zetmate/guitar-scale#2]
**Steps to reproduce:**
1) Select double harmonic scale for some root note (e.g. A or C#)

Case 1 (A double harmonic is selected):
![изображение](https://github.com/user-attachments/assets/7975096e-899c-4faa-ace4-ef427f4a944d)

Case 2 (C# double harmonic is selected):
![изображение](https://github.com/user-attachments/assets/fe50a155-f442-4c6d-b1a1-1200d9ec1f1f)

**Result:**
Note naming contains note duplications 
For e.g. A A# in the first case
For e.g D♭ D in the second case

**Expected result:**
Notes shown with correct flat or sharp values 

In the first case it should be B♭ instead of A# as it's alteration for B from the original major scale
In the second it should be E♭♭ instead of D as it's alteration for E♭ from the original major scale

**Comment by zetmate** [comment]
will be like this in the next release
![image](https://github.com/user-attachments/assets/0752b85c-b0e5-46b7-b1c9-85928de07a7c)

**Comment by zetmate** [comment]
But before I merge it @DmitryRosenblatt can you please confirm this is what you actually wanna see?
![image](https://github.com/user-attachments/assets/519609c3-81af-45c8-bc2a-6e89f44c3305)
